# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identity', models.CharField(choices=[('ADVISOR', 'Advisor'), ('MS', 'MS student'), ('PHD', 'PhD student'), ('INTERN', 'Intern student'), ('ASSISTANT', 'Assitant')], default='MS', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('picture', models.ImageField(blank=True, upload_to=b'')),
                ('join_date', models.DateField(auto_now_add=True)),
                ('graduate_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
