# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('post_time', models.DateTimeField()),
                ('content', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to=website.models.activity_picture_path)),
            ],
            options={
                'ordering': ['-post_time'],
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, upload_to=website.models.member_picture_path),
        ),
    ]
