# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='thesis',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='identity',
            field=models.CharField(choices=[('aADVISOR', 'Advisor'), ('cMS', 'Master'), ('bPHD', 'PhD'), ('dINTERN', 'Intern'), ('eASSISTANT', 'Assitant')], default='cMS', max_length=10),
        ),
    ]
