# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_reorder_identity_thesis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year']},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='index',
            new_name='pages',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='at',
            new_name='venue',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='date',
        ),
        migrations.AddField(
            model_name='publication',
            name='dblp_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='paper_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
    ]
