# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
