# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_map_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='paper_type',
            field=models.CharField(choices=[('Conference and Workshop Papers', 'Conference and Workshop Papers'), ('Journal Articles', 'Journal Articles'), ('Technical Report', 'Technical Report'), ('Patent', 'Patent'), ('Other', 'Other')], max_length=255),
        ),
    ]
