# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_member_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='author_members',
            field=models.ManyToManyField(to='website.Member'),
        ),
        migrations.AlterField(
            model_name='membermeta',
            name='category',
            field=models.CharField(help_text='Awards and Honors, Editorial Position, General and Program Chairs, or Member of Committee', max_length=255),
        ),
    ]
