# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 09:55
from __future__ import unicode_literals

from django.db import migrations, models

BEST_PAPER_STR = 'Best paper award'

def fill_best_paper(apps, schema_editor):
    """
    There may be different type of awards for each publication that are
    not best paper award. Instead of identifying whether a publication
    is a best paper, we use the field `awards` to record all awards a
    publication receives in a semicolon-separated format.
    In this migration, we fill the awards field with 'Best paper award'
    for each publication that is originally recognized as best paper.
    """
    Publication = apps.get_model('website', 'Publication')
    for best_paper in Publication.objects.filter(best_paper=True):
        best_paper.awards = BEST_PAPER_STR
        best_paper.save()

def rev_func(apps, schema_editor):
    """
    Reverse `fill_best_paper`.
    """
    Publication = apps.get_model('website', 'Publication')
    for best_paper in Publication.objects.filter(awards__icontains=BEST_PAPER_STR):
        best_paper.best_paper = True
        best_paper.save()

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_publication_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='awards',
            field=models.CharField(blank=True, help_text='Separated with semicolon. Ex: Best paper award; Another award', max_length=255),
        ),
        migrations.RunPython(fill_best_paper, rev_func),
        migrations.RemoveField(
            model_name='publication',
            name='best_paper',
        ),
    ]
