# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def fill_order(apps, schema_editor):
    Publication = apps.get_model('website', 'Publication')
    PublicationAuthor = apps.get_model('website', 'PublicationAuthor')

    for pub in Publication.objects.all():
        for i, author in enumerate(pub.author_members.all()):
            PublicationAuthor.objects.create(
                author=author,
                publication=pub,
                order=i + 1,
            )
        pub.author_members.clear()

def rev_func(apps, schema_editor):
    PublicationAuthor = apps.get_model('website', 'PublicationAuthor')

    for pa in PublicationAuthor.objects.all():
        pa.publication.author_members.add(pa.author)

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_generalize_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Member')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Publication')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, help_text='Ex: 10.1145/2892242.2892246', max_length=100),
        ),
        migrations.RunPython(fill_order, rev_func),
        migrations.RemoveField(
            model_name='publication',
            name='author_members',
        ),
        migrations.AddField(
            model_name='publication',
            name='author_members',
            field=models.ManyToManyField(through='website.PublicationAuthor', to='website.Member'),
        ),
        migrations.AlterUniqueTogether(
            name='publicationauthor',
            unique_together=set([('publication', 'author'), ('publication', 'order')]),
        ),
    ]
