# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('present_type', models.CharField(choices=[('PAPER', 'Paper presentation'), ('PROGRESS', 'Progress report')], max_length=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PresentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.MeetingHistory')),
                ('presenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Member')),
            ],
            options={
                'ordering': ['meeting'],
            },
        ),
        migrations.CreateModel(
            name='PresentRotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('presenter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.Member')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='meetinghistory',
            name='last_rotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.PresentRotation'),
        ),
    ]
