# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_reorder_identity_thesis'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinghistory',
            name='presenters',
            field=models.ManyToManyField(through='meeting.PresentHistory', to='website.Member'),
        ),
    ]
