# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_presenters'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSkip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
