# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_map_member_user'),
        ('meeting', '0003_meeting_skip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ONTIME', 'present on time'), ('BUSINESS', 'on business'), ('LATE', 'late'), ('LEAVE_BEFORE', 'leave in advance'), ('LEAVE_AFTER', 'leave afterwards'), ('ABSENT', 'absent')], max_length=15)),
                ('reason', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='meetinghistory',
            name='presenters',
            field=models.ManyToManyField(related_name='presenting', through='meeting.PresentHistory', to='website.Member'),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.MeetingHistory'),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Member'),
        ),
        migrations.AddField(
            model_name='meetinghistory',
            name='attendance',
            field=models.ManyToManyField(related_name='attending', through='meeting.MeetingAttendance', to='website.Member'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingattendance',
            unique_together=set([('meeting', 'member')]),
        ),
    ]
