# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 10:24
from __future__ import unicode_literals

from django.db import migrations, models

def inherit_meeting_type(apps, schema_editor):
    """
    We are going to categorize the present type in a more fine-grain
    unit: each presentation, instead of original 'each meeting'. During
    the migration, to preserve the original present type for each presentation,
    we run this script to get each presentation the present type of the
    meeting it belongs to.
    """
    PresentHistory = apps.get_model('meeting', 'PresentHistory')
    for presentation in PresentHistory.objects.all():
        if presentation.meeting:
            presentation.present_type = presentation.meeting.present_type
            presentation.save()

def rev_func(apps, schema_editor):
    MeetingHistory = apps.get_model('meeting', 'MeetingHistory')
    for meeting in MeetingHistory.objects.all():
        if meeting.presenthistory_set.exists():
            meeting.present_type = meeting.presenthistory_set.all()[0].present_type
            meeting.save()

class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenthistory',
            name='is_specially_arranged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presenthistory',
            name='present_type',
            field=models.CharField(choices=[('PAPER', 'Paper presentation'), ('PROGRESS', 'Progress report'), ('OTHER', 'Other')], default='OTHER', max_length=10),
            preserve_default=False,
        ),
        migrations.RunPython(inherit_meeting_type, rev_func),
        migrations.RemoveField(
            model_name='meetinghistory',
            name='present_type',
        ),
    ]
