# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def remove_nullhistory(apps, schema_editor):
    PresentHistory = apps.get_model('meeting', 'PresentHistory')
    null_rows = PresentHistory.objects.filter(meeting=None)

    if null_rows.exists():
        print ''
        print '\033[1;31mWarning: This migration will remove all present history with null meeting, which include:\033[m'
        print '\t' + '\n\t'.join(map(lambda r: '%s %s' % (r.presenter.name, r.content), null_rows))
        print 'Note that this is not reversible!'
        raw_input('Press Enter to continue...')

        null_rows.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_change_meeting_type'),
    ]

    operations = [
        migrations.RunPython(remove_nullhistory),
        migrations.AlterField(
            model_name='presenthistory',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meeting.MeetingHistory'),
        ),
    ]
