# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_no_null_presenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinghistory',
            name='gcal_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
