# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_google_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinghistory',
            name='slack_ts',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
